/**
 * Ilovada ishlatiladigan barcha ikonkalar shu yerda nomlanadi.
 * Manba: react-icons/lu (Lucide) — bir xil uslubdagi chiziqli ikonkalar.
 */
export {
  LuLayoutDashboard as IcoDashboard,
  LuSchool as IcoClasses,
  LuUsers as IcoTeachers,
  LuBookOpen as IcoCurriculum,
  LuClipboardList as IcoTarif,
  LuPin as IcoRules,
  LuSettings2 as IcoGenerate,
  LuCalendarDays as IcoSchedule,
  LuShieldCheck as IcoReport,
  LuPlus as IcoPlus,
  LuX as IcoClose,
  LuTrash2 as IcoTrash,
  LuPencil as IcoEdit,
  LuPrinter as IcoPrint,
  LuDownload as IcoDownload,
  LuPlay as IcoPlay,
  LuRotateCcw as IcoRerun,
  LuRefreshCw as IcoReset,
  LuLock as IcoLock,
  LuLockOpen as IcoUnlock,
  LuArrowLeftRight as IcoTransfer,
  LuWandSparkles as IcoAuto,
  LuSearch as IcoSearch,
  LuSun as IcoSun,
  LuMoon as IcoMoon,
  LuMonitor as IcoSystem,
  LuTriangleAlert as IcoWarn,
  LuCircleCheck as IcoOk,
  LuCircleAlert as IcoError,
  LuInfo as IcoInfo,
  LuChevronRight as IcoNext,
  LuSquare as IcoStop,
  LuAward as IcoCategory,
  LuClock as IcoClock,
  LuFilter as IcoFilter,
  LuUpload as IcoUpload,
  LuFileSpreadsheet as IcoExcel,
  LuFileDown as IcoTemplate,
} from 'react-icons/lu'
